#!/bin/bash
pyfile="$PYFILE"
if [ -z "$pyfile" ]; then
	echo "Error: Environment variable \$PYFILE is not set."
	exit 1
elif [ ! -f "$pyfile" ]; then
	echo "Error: File $pyfile not found."
	exit 1
fi
	python3 "$pyfile"
